### ISSUE TITLE
Apple M1 - Lando v3.6.4 - Docker Desktop v3.6.0.5487 - Database Pull Failed

### ISSUE THREAD

**Issue by refringe** [lando/pantheon#130]
I'm having an issue pulling databases down locally.

The process begins pulling the export down for roughly 5-25 seconds and then dies before it's finished. I've tried recreating from scratch and two different sites. Always the same result.

`lando pull --code=none --files=none --database=live --vvv`

[...]

```
Making sure your site is awake...
 [notice] OK >> site.pantheonsite.io responded
Pulling your database... This miiiiight take a minute
 [notice] Command: site.live -- wp db export [Exit: 0]              ]
66.8MiB 0:00:22 [2.98MiB/s] [          <=>                                     ]
Checking db pull for expected tables...
Database pull failed...
site 20:00:44 DEBUG ==> process pid5 finished with exit code 1
site 20:00:44 DEBUG ==> engine is up.
lando           20:00:44 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
lando           20:00:44 DEBUG ==> reported data command=lando pull, context=local, devMode=false, instance=instanceid, nodeVersion=v14.18.3, mode=cli, type=Darwin, platform=darwin, release=21.5.0, arch=arm64, product=lando, version=3.6.4, message=Database pull failed... , stack=Error: Database pull failed...
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (shell.js)
    at Object.dockerExec (utils.js)
    at /snapshot/cli/plugins/lando-tooling/lib/build.js
From previous event:
    at Object.run (build.js)
From previous event:
    at /snapshot/cli/lib/bootstrap.js
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (cli.js)
    at Object.runCommand (command.js:238:44)
    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)
    at Function.get [as argv] (yargs.js:1004:21)
    at Cli.init (cli.js)
    at Cli.run (cli.js)
    at Object.<anonymous> (lando.js)
    at Module._compile (bootstrap.js:1794:22)
    at Function.runMain (bootstrap.js:1847:12)
    at internal/main/run_main_module.js:17:47, action=error, created=2022-06-23T00:00:44.301Z
```

**Comment by refringe** [comment]
If it helps nail down the issue, the separate process of downloading a DB backup and manually importing it works fine. It's just the pull function that is failing. 🤷‍♂️

**Comment by ethangeorgi** [comment]
Assuming you've resolved this issue by now. If the issue persists, and updating Lando does not resolve it, please re-open this issue.
