### ISSUE TITLE
[WP-CLI] Uncaught Error: Undefined constant "WP_HOME"

### ISSUE THREAD

**Issue by bfcmaintenance** [lando/pantheon#167]
I've inherited a codebase that uses the lando pantheon wordpress recipe. the site seems to use a modified [bedrock](https://roots.io/bedrock/)-style folder structure. my local site is up and running but I am unable to use WP-CLI. `lando wp --info` seems to work though.

    % system_profiler SPHardwareDataType
    Hardware:
    
        Hardware Overview:
    
          Model Name: MacBook Air
          Model Identifier: MacBookAir10,1
          Chip: Apple M1
          Total Number of Cores: 8 (4 performance and 4 efficiency)
          Memory: 16 GB
          System Firmware Version: 7429.61.2
          OS Loader Version: 6723.140.2

    % cat .lando.yml
    name: ***
    recipe: pantheon
    config:
      webroot: web
      framework: wordpress
      site: ***
      id: ***

    % lando wp --info
    OS:	Linux 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64
    Shell:
    PHP binary:	/usr/local/bin/php
    PHP version:	8.1.14
    php.ini used:
    MySQL binary:	/usr/bin/mysql
    MySQL version:	mysql  Ver 15.1 Distrib 10.5.18-MariaDB, for debian-linux-gnu (aarch64) using  EditLine wrapper
    SQL modes:
    WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
    WP-CLI vendor dir:	phar://wp-cli.phar/vendor
    WP_CLI phar path:	/app
    WP-CLI packages dir:
    WP-CLI cache dir:	/var/www/.wp-cli/cache
    WP-CLI global config:	/var/www/.wp-cli/config.yml
    WP-CLI project config:	/app/wp-cli.yml
    WP-CLI version:	2.7.1

    % lando wp
    PHP Fatal error:  Uncaught Error: Undefined constant "WP_HOME" in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1296) : eval()'d code:217
    Stack trace:
    #0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1296): eval()
    #1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
    #2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
    #3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
    #5 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
    #6 /usr/local/bin/wp(4): include('phar:///usr/loc...')
    #7 {main}
      thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1296) : eval()'d code on line 217

i've tried:
- `lando rebuild` and `lando rebuild appserver`
- hardcoding `WP_HOME` in `wp-config.php` and `.env`
- `lando ssh`ing and getting a new wp-cli.phar binary; when i do this it seems to work momentarily (running `lando wp` prints the info page) but then stops working again
- deleting the global config in the lando container (at `/var/www/.wp-cli/config.yml`)

I really have no idea where in the toolchain this issue is popping up but i haven't had any issues using wp-cli on lando projects that are using the wordpress recipe instead of the pantheon wordpress one.

**Comment by bfcmaintenance** [comment]
it was an issue with my wp-config.php; lando doesn't appear to be setting `$_SERVER['HTTP_HOST']`. i modified the config to fallback to `$_SERVER['LANDO_HOST_IP']` and it appears to work again.
