### ISSUE TITLE
Unhandled rejection SyntaxError: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by brookemahoney** [lando/pantheon#28]
3.0.7 on Mac Mojave

When I try any lando command from any path, including just running `lando` with no arguments, I get the following error:

```
$ lando
Unhandled rejection SyntaxError: Unexpected token  in JSON at position 0
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at /snapshot/lando/build/cli/plugins/lando-pantheon/lib/utils.js
    at arrayMap (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:639:23)
    at Function.map (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9556:14)
    at interceptor (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:16993:35)
    at thru (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:8797:14)
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4374:28
    at arrayReduce (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4373:14)
    at LazyWrapper.lazyValue [as value] (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:1859:16)
    at baseWrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4371:25)
    at LodashWrapper.wrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9052:14)
    at Object.getTerminusTokens (/snapshot/lando/build/cli/plugins/lando-pantheon/lib/utils.js)
    at getTokens (/snapshot/lando/build/cli/plugins/lando-pantheon/recipes/pantheon/init.js)
    at Object.options (/snapshot/lando/build/cli/plugins/lando-pantheon/recipes/pantheon/init.js)
    at /snapshot/lando/build/cli/plugins/lando-recipes/lib/options.js
From previous event:
    at processImmediate (internal/timers.js:439:21)
```

**Tell us more**

I have tried uninstalling and reinstalling Lando (including removing ~/.lando) and Docker multiple times.
I've tried with 3.0.7, 3.0.5, and 3.0.1.
I've searched the issue queue here and haven't found anything in all the issues ever filed.
I updated my version of Node to the latest LTS which didn't help.
I've spent all today, Sunday, trying to get it to work on a personal project. Yesterday it was working fine; I had multiple drupal 8 instances running without any issue. I have been using it all week on yet another project. The only real difference about the project I was trying to get to work today is that it's a Pantheon recipe. I was in the middle of setting up authorization with Terminus and setting up a pantheon.yml file, but started to run into errors like the one above.

Does this bug prevent you from using lando? Yes

**Comment by djassie** [comment]
I got the similar error - which make me come here 

The lando file was big, but there was small error - which was causing the problem. 

````yaml
name: Drupalmerc
recipe: drupal9
config:
  build:
    run_scripts: true
  composer_version: '2.4.3'
  via: apache
  drush: true
  php: '8.1'
````

Now, after lot of head crunching, the **name** should be all small 

so, I have change only the **name** key

Changed : 

````yaml
name: drupalmerc
...
````
